### ISSUE TITLE
installing pylab

### ISSUE THREAD

**Issue by rdmueller** [ankitaggarwal011/PiScope#1]
I had some problems to get pylab up and running on my pi. I tried to install them through `pip install pylab`.
Maybe you could mention that the needed dependencies can be installed through
`sudo apt-get install python-numpy python-scipy python-matplotlib python-tk`

**Comment by ankitaggarwal011** [comment]
Good suggestion :+1:, I also had this same problem when I started using Raspberry Pi.
This information will be useful. Thanks @rdmueller. 

Could you please add this in the documentation through a pull request, if that's okay with you. Thanks.

**Comment by ankitaggarwal011** [comment]
Closed by #2.
